### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by vico93** [Schauweg/Login-Toast#1]
I got [this crash](https://hastebin.com/oculecenif.cs) when trying to boot the game with your mod.

Also my [`latest.log`](https://hastebin.com/qogahoveco.rb)

**Comment by vico93** [comment]
Seems like hastebin is having a bad time, here the crash-report on gist:

https://gist.github.com/vico93/a94cc1f38337d8f464c0112ccfa67398

**Comment by Schauweg** [comment]
Thank you for your bugreport! Was a stupid oversight by me. I uploaded a fixed version on curseforge.

**Comment by vico93** [comment]
Thanks a lot! Its working now!
